# Generated by Django 4.1.7 on 2023-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
