# Generated by Django 4.1.7 on 2023-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miperfil',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='miperfil',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='miperfil',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
