# Generated by Django 4.1.7 on 2023-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfiles', '0002_miperfil_apellido_miperfil_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miperfil',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
