# Generated by Django 4.1.7 on 2023-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfiles', '0003_miperfil_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miperfil',
            name='bio',
            field=models.TextField(default='', max_length=100),
        ),
    ]
