# Generated by Django 4.1.7 on 2023-05-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfiles', '0005_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miperfil',
            name='bio',
        ),
    ]
