# Generated by Django 4.1.7 on 2023-04-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.TimeField()),
                ('texto', models.TextField()),
            ],
        ),
    ]
