# Generated by Django 4.1.7 on 2023-05-03 19:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='texto',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
