# Generated by Django 4.1.7 on 2023-05-03 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_posteos_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
